FROM ubuntu:20.04

MAINTAINER Scott Swindell "sswindell@mmto.org"

#Setup timezone and install indi-sbig dependencies
ENV TIMEZONE US/Arizona
RUN ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime && echo $TIMEZONE > /etc/timezone



RUN apt-get update
RUN apt-get -y install \
	cmake g++ libnova-dev zlib1g-dev git lsb-release


#add-apt-repository needs lsb-release first
RUN apt install -y software-properties-common

RUN add-apt-repository -y ppa:mutlaqja/ppa && \
        apt update && \
        apt install -y \
        libindi-dev indi-sbig git


RUN mkdir /home/indi &&\
	useradd indi


RUN apt -y install python3.8 python3-pip

RUN pip install sqlalchemy && \
 pip install asyncpg && \
 pip install asyncssh && \
 pip install rsa && \
 pip install requests && \
 pip install git+https://github.com/srswinde/py-saomsg

COPY start_indi.sh /home/indi/start_indi.sh
COPY dummy_driver.py /home/indi/dummy_driver.py

CMD /home/indi/start_indi.sh

